apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: datanode
  name: datanode
spec:
  ports:
  - name: "50075"
    port: 50075
    targetPort: 50075
  selector:
    io.kompose.service: datanode
status:
  loadBalancer: {}
