apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: recommender
spec:
  selector:
    matchLabels:
      app: recommender
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
      - name: hdfs-namenode
        image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
        ports:
        - containerPort: 50070
