version: '3.6' 
services:
  master:
    image: chookly/bdfi:spark-master
    command: spark-class org.apache.spark.deploy.master.Master -h localhost
    #command: /root/spark-2.1.3-bin-hadoop2.7/sbin/start-master.sh --host 127.0.0.1
    networks: 
      myNetwork:
        aliases:
          - spark-master
    environment:
      #MASTER: spark://localhost:7077
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 7077:7077
      - 8080:8080

  worker:
    image: chookly/bdfi:spark-worker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks: 
      myNetwork:
        aliases:
          - spark-worker
    depends_on: 
      - master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 8081:8081

  namenode:
    image: chookly/bdfi:namenode
    #command: hadoop fs -copyFromLocal /datasetFiles /
    networks: 
      myNetwork:
        aliases:
          - hdfs-namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070

  datanode:
    image: chookly/bdfi:datanode
    networks: 
      myNetwork:
        aliases:
          - hdfs-datanode
    depends_on: 
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075

networks:
  myNetwork: