version: '3.6' 
services:
  master:
    image: chookly/bdfi:master
    command: spark-class org.apache.spark.deploy.master.Master -h 10.0.1.3
    networks: 
      myNetwork:
        aliases:
          - maestro
    environment:
      MASTER: spark://10.0.1.3:7077
      SPARK_PUBLIC_DNS: 127.0.0.11
    ports:
      - 7077:7077
      - 8080:8080

  worker:
    image: chookly/bdfi:worker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://10.0.1.3:7077
    networks: 
      myNetwork:
        aliases:
          - esclavo
    depends_on: 
      - master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: 127.0.0.11
    ports:
      - 8081:8081

  namenode:
    image: chookly/bdfi:namenode
    #command: hadoop fs -copyFromLocal /datasetFiles /
    networks: 
      myNetwork:
        aliases:
          - hdfs-namenode
    depends_on: 
      - worker
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop1.env
    ports:
      - 50070:50070

  datanode:
    image: chookly/bdfi:datanode
    networks: 
      myNetwork:
        aliases:
          - hdfs-datanode
    depends_on: 
      - namenode
    env_file:
      - ./hadoop2.env
    ports:
      - 50075:50075

networks:
  myNetwork: