apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: namenode
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: test
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:8020
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: root
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: '*'
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: '*'
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
        image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
        name: namenode
        ports:
        - containerPort: 50070
        volumeMounts:
            - name: hdfs-data
              mountPath: /hadoop/dfs/data
        resources: {}
      restartPolicy: Always
status: {}
