version: '3' 
services:
  master:
    image: chookly/bdfi:spark-master
#    networks: 
#      - testnet
    command: spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 7077:7077
      - 8080:8080

  worker:
    image: chookly/bdfi:spark-worker
#    networks: 
#      - testnet
    command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 8081:8081

  namenode:
    image: chookly/bdfi:namenode
#    networks: 
#      - testnet
    #command: hadoop fs -copyFromLocal /datasetFiles /
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
#    networks: 
#      - testnet
    hostname: datanode
    depends_on: 
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075